_BASE_: "../allrand/UniCOAL/6_final.yml"

loaders:
  batch_size: 64
  thickness: [6,]
  slice_num: 4
  all_hr: False
  raw_internal_path_in: [T1_blur, ]
  raw_internal_path_out: [T1, PD, T2, ]
  test:
    target_modality: 0

