_BASE_: "./5_high_lr.yml"

loaders:
  dataset_mode: cmsreval
  batch_size: 32
  serial_batches: False
  num_threads: 8
  raw_internal_path_out: [T1, PD, T2, ]
  test:
    target_modality: 1
  all_hr: True
  thickness: [4,]
  out_thickness: 4.0
  slice_num: 4

name: 'ixi_stylegan3_allrand_modulatedenc_more_thickness_morelr'
