_BASE_: "../../ixi/multitask/base.yml"

loaders:
  raw_internal_path_in: [t2, ]
  raw_internal_path_out: [flair, ]
  label_internal_path: [seg, ]
  train:
    file_paths: ['../../data/public_data/brats2019/h5list_translation/CBICA_train.txt', 
                '../../data/public_data/brats2019/h5list_translation/TCIA_train.txt']
  test:
    ori_file_path: ../../data/public_data/brats2019/cropped
    file_paths: ['../../data/public_data/brats2019/h5list_translation/CBICA_val.txt', 
                '../../data/public_data/brats2019/h5list_translation/TCIA_val.txt']

